const newTemplatesDataBackend = [
  // ==================== WEDDING (10) ====================
  {
    id: "tpl-wedding-1",
    name: "Celestial Romance Vows",
    category: "Wedding",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #fdfcfb 0%, #e2d1c3 100%)",
      accentColor: "#d4af37",
      emoji: "💍",
      host: "Hosted by Eleanor & Julian",
      venue: "Starlight Estate & Conservatory",
      description: "Join us for an enchanting evening of love, laughter, and lifelong memories under the stars.",
      imageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#FAF8F5",
      textColor: "#2D1B3D",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Playfair Display",
      buttonColor: "#d4af37",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-wedding-2",
    name: "Botanical Glasshouse Union",
    category: "Wedding",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #e8f5e9 0%, #c8e6c9 100%)",
      accentColor: "#2e7d32",
      emoji: "🌿",
      host: "Hosted by Chloe & Marcus",
      venue: "The Orchid Glasshouse Gardens",
      description: "Step into our serene botanical sanctuary as we exchange vows surrounded by lush greenery.",
      imageUrl: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#F4F7F4",
      textColor: "#1C351E",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Lora",
      buttonColor: "#2e7d32",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-wedding-3",
    name: "Sunset Oceanfront Vows",
    category: "Wedding",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)",
      accentColor: "#e06d53",
      emoji: "🌅",
      host: "Hosted by Maya & Jonathan",
      venue: "Malibu Cove Ocean Villa",
      description: "Witness our promises at golden hour along the sun-kissed shores of Malibu Beach.",
      imageUrl: "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#FFF9F5",
      textColor: "#3A2219",
      titleSize: 50,
      fontWeight: "700",
      fontFamily: "Great Vibes",
      buttonColor: "#e06d53",
      buttonRadius: 14,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-wedding-4",
    name: "Minimalist Modern Love",
    category: "Wedding",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #f5f5f5 0%, #e0e0e0 100%)",
      accentColor: "#333333",
      emoji: "🕊️",
      host: "Hosted by Sophia & David",
      venue: "The Loft Contemporary Gallery",
      description: "An elegant, minimalist celebration of partnership, fine art, and contemporary design.",
      imageUrl: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#FAFAFA",
      textColor: "#111111",
      titleSize: 44,
      fontWeight: "600",
      fontFamily: "Inter",
      buttonColor: "#222222",
      buttonRadius: 6,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-wedding-5",
    name: "Rustic Terracotta Barn Wedding",
    category: "Wedding",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #f7d6c8 0%, #e59882 100%)",
      accentColor: "#b85636",
      emoji: "🌾",
      host: "Hosted by Hannah & Tyler",
      venue: "Whispering Pines Heritage Barn",
      description: "Gather with us in the cozy countryside for a rustic dinner, live acoustic music, and barn dancing.",
      imageUrl: "https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#FAF4F0",
      textColor: "#3D241C",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Merriweather",
      buttonColor: "#b85636",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-wedding-6",
    name: "Vintage European Chateau Affair",
    category: "Wedding",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #ede7f6 0%, #d1c4e9 100%)",
      accentColor: "#673ab7",
      emoji: "🏰",
      host: "Hosted by Isabelle & Henri",
      venue: "Chateau Grandeur Courtyard",
      description: "An romantic evening inspired by classic European elegance, fine wine, and candlelit waltzes.",
      imageUrl: "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#F7F5FA",
      textColor: "#261738",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Cinzel",
      buttonColor: "#673ab7",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-wedding-7",
    name: "Royal Navy & Gold Gala",
    category: "Wedding",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #1a237e 0%, #0d47a1 100%)",
      accentColor: "#ffd700",
      emoji: "👑",
      host: "Hosted by Victoria & Alexander",
      venue: "The Imperial Palace Ballroom",
      description: "A majestic black-tie affair filled with opulent gold decor, gourmet dining, and royal festivities.",
      imageUrl: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#0B132B",
      textColor: "#F4F5F6",
      titleSize: 50,
      fontWeight: "800",
      fontFamily: "Playfair Display",
      buttonColor: "#ffd700",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-wedding-8",
    name: "Bohemian Woodland Magic",
    category: "Wedding",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #d7ccc8 0%, #a1887f 100%)",
      accentColor: "#5d4037",
      emoji: "🌲",
      host: "Hosted by Freya & Noah",
      venue: "Redwood Canopy Sanctuary",
      description: "Under majestic redwood trees, join us for a whimsical bohemian wedding celebration.",
      imageUrl: "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#F5F2F0",
      textColor: "#2C1D18",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Lora",
      buttonColor: "#5d4037",
      buttonRadius: 16,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-wedding-9",
    name: "Tropical Paradise Union",
    category: "Wedding",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #e0f7fa 0%, #80deea 100%)",
      accentColor: "#00838f",
      emoji: "🌺",
      host: "Hosted by Leilani & Kai",
      venue: "Bali Palm Beach Villa",
      description: "Island breeze, ocean acoustic music, and tropical cocktails as we tie the knot in paradise.",
      imageUrl: "https://images.unsplash.com/photo-1544078751-58fee2d8a03b?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#F0FAFC",
      textColor: "#00363A",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Montserrat",
      buttonColor: "#00838f",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-wedding-10",
    name: "Classic Rose Gold Romance",
    category: "Wedding",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #fce4ec 0%, #f8bbd0 100%)",
      accentColor: "#c2185b",
      emoji: "🌹",
      host: "Hosted by Olivia & William",
      venue: "The Rosewood Hotel Ballroom",
      description: "Celebrate our eternal bond with a romantic dinner, champagne toast, and classic waltz.",
      imageUrl: "https://images.unsplash.com/photo-1532712938310-34cb3982ef74?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#FAF2F5",
      textColor: "#3B081B",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Playfair Display",
      buttonColor: "#c2185b",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },

  // ==================== BABY SHOWER (10) ====================
  {
    id: "tpl-babyshower-1",
    name: "Little Starry Night Shower",
    category: "Baby Shower",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #e1f5fe 0%, #b3e5fc 100%)",
      accentColor: "#0288d1",
      emoji: "⭐",
      host: "Hosted by The Miller Family",
      venue: "Starlight Garden Cafe",
      description: "Help us welcome our little shining star with sweet treats, fun baby trivia, and joyful gifts!",
      imageUrl: "https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#F4FAFD",
      textColor: "#013755",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Poppins",
      buttonColor: "#0288d1",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-babyshower-2",
    name: "Woodland Forest Friends Shower",
    category: "Baby Shower",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #d7ccc8 0%, #bcaaa4 100%)",
      accentColor: "#4e342e",
      emoji: "🦊",
      host: "Hosted by Sarah & Benjamin",
      venue: "Pinewood Lodge Pavilion",
      description: "Join us in welcoming our cozy woodland miracle with rustic games, hot cocoa, and sweet memories.",
      imageUrl: "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#FAF7F5",
      textColor: "#2C1B17",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Lora",
      buttonColor: "#4e342e",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-babyshower-3",
    name: "Pastel Balloon Fiesta Shower",
    category: "Baby Shower",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #f8bbd0 0%, #e1bee7 100%)",
      accentColor: "#ab47bc",
      emoji: "🎈",
      host: "Hosted by Jessica & Friends",
      venue: "Sunshine Tea House",
      description: "A whimsical afternoon filled with pastel balloons, afternoon high tea, and baby shower games.",
      imageUrl: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#FCF6FD",
      textColor: "#380E40",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Outfit",
      buttonColor: "#ab47bc",
      buttonRadius: 14,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-babyshower-4",
    name: "Teddy Bear Picnic Shower",
    category: "Baby Shower",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #fff8e1 0%, #ffecb3 100%)",
      accentColor: "#ff8f00",
      emoji: "🧸",
      host: "Hosted by Grandma Rose",
      venue: "Sunny Meadows Park",
      description: "Bring your favorite teddy bear memories and celebrate baby's upcoming arrival under the oak trees.",
      imageUrl: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#FFFCF5",
      textColor: "#4A2B00",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Merriweather",
      buttonColor: "#ff8f00",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-babyshower-5",
    name: "Under the Sea Splash Shower",
    category: "Baby Shower",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #e0f2f1 0%, #80cbd4 100%)",
      accentColor: "#00695c",
      emoji: "🐬",
      host: "Hosted by Emily & Mark",
      venue: "Ocean Vista Hall",
      description: "Dive into a cute nautical baby shower with sea-themed treats, refreshing drinks, and ocean vibes.",
      imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#F2FAF9",
      textColor: "#002B26",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Montserrat",
      buttonColor: "#00695c",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-babyshower-6",
    name: "Floral Garden Bloom Shower",
    category: "Baby Shower",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #fce4ec 0%, #f48fb1 100%)",
      accentColor: "#ad1457",
      emoji: "🌸",
      host: "Hosted by The Floral Sisterhood",
      venue: "Rosewood Botanical Tea Garden",
      description: "Celebrate amidst blooming roses and floral garlands with gourmet finger sandwiches and lemonade.",
      imageUrl: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#FAF2F5",
      textColor: "#420019",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Playfair Display",
      buttonColor: "#ad1457",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-babyshower-7",
    name: "Over the Rainbow Shower",
    category: "Baby Shower",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #fff3e0 0%, #ffe0b2 100%)",
      accentColor: "#f57c00",
      emoji: "🌈",
      host: "Hosted by Laura & Friends",
      venue: "Skylight Conservatory",
      description: "A bright rainbow-themed baby shower filled with vibrant colors, sweet pastries, and laughter.",
      imageUrl: "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#FFFDF7",
      textColor: "#3E1E00",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Outfit",
      buttonColor: "#f57c00",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },

  {
    id: "tpl-babyshower-9",
    name: "Cloud & Moon Starlight Shower",
    category: "Baby Shower",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #e8eaf6 0%, #c5cae9 100%)",
      accentColor: "#3f51b5",
      emoji: "🌙",
      host: "Hosted by The Carter Family",
      venue: "Heavenly Heights Terrace",
      description: "An evening moonlit baby shower with fluffy white cloud decorations and starry twinkling lights.",
      imageUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#F5F6FA",
      textColor: "#121A42",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Poppins",
      buttonColor: "#3f51b5",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-babyshower-10",
    name: "Safari Jungle Adventure Shower",
    category: "Baby Shower",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #e8f5e9 0%, #a5d6a7 100%)",
      accentColor: "#388e3c",
      emoji: "🦁",
      host: "Hosted by Daniel & Amanda",
      venue: "Wildwood Eco Lodge",
      description: "A fun jungle safari baby shower featuring adorable animal decor, tropical punch, and games.",
      imageUrl: "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#F4FAF5",
      textColor: "#0E2B0F",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Inter",
      buttonColor: "#388e3c",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },

  // ==================== CORPORATE (10) ====================
  {
    id: "tpl-corporate-1",
    name: "Tech Summit & Keynote 2026",
    category: "Corporate",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)",
      accentColor: "#38bdf8",
      emoji: "💻",
      host: "Hosted by Nexus AI Labs",
      venue: "Silicon Convention Center",
      description: "Connect with global industry leaders, tech visionaries, and venture capitalists shaping the tech ecosystem.",
      imageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#0F172A",
      textColor: "#F8FAFC",
      titleSize: 44,
      fontWeight: "800",
      fontFamily: "Inter",
      buttonColor: "#38bdf8",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-corporate-2",
    name: "Executive Leadership Retreat",
    category: "Corporate",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #1c3144 0%, #000000 100%)",
      accentColor: "#d00000",
      emoji: "🏔️",
      host: "Hosted by Apex Global Corp",
      venue: "Mountain Peak Eco Resort",
      description: "An exclusive weekend retreat focusing on executive alignment, high-stakes decision making, and wellness.",
      imageUrl: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#111827",
      textColor: "#F9FAFB",
      titleSize: 44,
      fontWeight: "700",
      fontFamily: "Montserrat",
      buttonColor: "#d00000",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-corporate-3",
    name: "Global Investor Pitch Night",
    category: "Corporate",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #2c3e50 0%, #000000 100%)",
      accentColor: "#f1c40f",
      emoji: "📈",
      host: "Hosted by Wall Street Venture Fund",
      venue: "Wall Street Tower - 50th Fl",
      description: "Top 10 pre-Series A tech startups present to leading angel investors, institutional VC funds, and partners.",
      imageUrl: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#161F28",
      textColor: "#FFFFFF",
      titleSize: 44,
      fontWeight: "700",
      fontFamily: "Inter",
      buttonColor: "#f1c40f",
      buttonRadius: 6,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-corporate-4",
    name: "AI Innovation Expo",
    category: "Corporate",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #4a148c 0%, #12005e 100%)",
      accentColor: "#00e5ff",
      emoji: "🤖",
      host: "Hosted by CyberTech Alliance",
      venue: "Metropolitan Cybertech Auditorium",
      description: "Discover hands-on AI demonstrations, autonomous robotics, generative models, and enterprise software.",
      imageUrl: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#0D0221",
      textColor: "#F0F4F8",
      titleSize: 44,
      fontWeight: "800",
      fontFamily: "Outfit",
      buttonColor: "#00e5ff",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-corporate-5",
    name: "Annual Corporate Excellence Awards",
    category: "Corporate",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #b71c1c 0%, #560027 100%)",
      accentColor: "#ffb300",
      emoji: "🏆",
      host: "Hosted by Enterprise Council",
      venue: "Starlight Grand Ballroom",
      description: "An elegant black-tie gala honoring extraordinary achievements, leadership milestones, and team success.",
      imageUrl: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#1A0508",
      textColor: "#FFF8E7",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Playfair Display",
      buttonColor: "#ffb300",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-corporate-6",
    name: "Product Launch Showcase",
    category: "Corporate",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #263238 0%, #000000 100%)",
      accentColor: "#ff6d00",
      emoji: "🚀",
      host: "Hosted by CloudScale Tech",
      venue: "Metropolitan Loft 44",
      description: "Live product demonstrations, keynote presentations from founders, and exclusive networking over cocktails.",
      imageUrl: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#12191D",
      textColor: "#ECEFF1",
      titleSize: 44,
      fontWeight: "700",
      fontFamily: "Inter",
      buttonColor: "#ff6d00",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-corporate-7",
    name: "Corporate Sustainability Forum",
    category: "Corporate",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #1b5e20 0%, #003300 100%)",
      accentColor: "#66bb6a",
      emoji: "🌱",
      host: "Hosted by Green Earth Enterprise",
      venue: "Eco Park Innovation Hub",
      description: "Join Fortune 500 executives and sustainability leaders discussing renewable energy, carbon offset, and ESG.",
      imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#0B1D0D",
      textColor: "#E8F5E9",
      titleSize: 44,
      fontWeight: "700",
      fontFamily: "Lora",
      buttonColor: "#66bb6a",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-corporate-8",
    name: "Fintech Breakthrough Summit",
    category: "Corporate",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #0d47a1 0%, #002171 100%)",
      accentColor: "#29b6f6",
      emoji: "💳",
      host: "Hosted by Capital One Network",
      venue: "Fintech Center Auditorium",
      description: "Explore the latest breakthroughs in digital payments, blockchain infrastructure, and banking security.",
      imageUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#06152D",
      textColor: "#E1F5FE",
      titleSize: 44,
      fontWeight: "700",
      fontFamily: "Montserrat",
      buttonColor: "#29b6f6",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-corporate-9",
    name: "Design & UX Thought Leadership",
    category: "Corporate",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #37474f 0%, #102027 100%)",
      accentColor: "#ff4081",
      emoji: "🎨",
      host: "Hosted by Creative Design Guild",
      venue: "Modernist Design Studio",
      description: "Workshops and roundtables on design systems, micro-interactions, and accessibility in digital products.",
      imageUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#182226",
      textColor: "#ECEFF1",
      titleSize: 44,
      fontWeight: "700",
      fontFamily: "Outfit",
      buttonColor: "#ff4081",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-corporate-10",
    name: "Venture Partner Private Dinner",
    category: "Corporate",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #212121 0%, #000000 100%)",
      accentColor: "#e040fb",
      emoji: "🍸",
      host: "Hosted by Horizon Ventures",
      venue: "Penthouse 54 Lounge",
      description: "An exclusive invite-only dinner for fund partners and unicorn founders to discuss strategic investments.",
      imageUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#121212",
      textColor: "#FAFAFA",
      titleSize: 44,
      fontWeight: "700",
      fontFamily: "Playfair Display",
      buttonColor: "#e040fb",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },

  // ==================== BIRTHDAY (10) ====================
  {
    id: "tpl-birthday-1",
    name: "Neon Glow Birthday Bash",
    category: "Birthday",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #880e4f 0%, #4a148c 100%)",
      accentColor: "#ff4081",
      emoji: "⚡",
      host: "Hosted by Alex & Crew",
      venue: "Club Velocity Lounge",
      description: "Wear your brightest neon outfit and dance all night with live DJ sets, laser lights, and glowing cocktails!",
      imageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#1E041B",
      textColor: "#FCE4EC",
      titleSize: 48,
      fontWeight: "800",
      fontFamily: "Outfit",
      buttonColor: "#ff4081",
      buttonRadius: 14,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-birthday-2",
    name: "Sweet 16 Sparkle Celebration",
    category: "Birthday",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #fce4ec 0%, #f8bbd0 100%)",
      accentColor: "#ec407a",
      emoji: "✨",
      host: "Hosted by The Davis Family",
      venue: "Crystal Ballroom",
      description: "Join Samantha for a glamorous Sweet 16 celebration featuring a red carpet entrance, photo booth, and dessert bar.",
      imageUrl: "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#FAF0F4",
      textColor: "#380617",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Playfair Display",
      buttonColor: "#ec407a",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-birthday-3",
    name: "Golden 50th Jubilee Birthday",
    category: "Birthday",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #fff8e1 0%, #ffecb3 100%)",
      accentColor: "#ffb300",
      emoji: "🥂",
      host: "Hosted by Robert's Children",
      venue: "Grand Heritage Hotel",
      description: "Honor five golden decades with fine wine, live jazz performance, and a retrospective photo slideshow.",
      imageUrl: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#FFFDF7",
      textColor: "#3B2700",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Cinzel",
      buttonColor: "#ffb300",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-birthday-4",
    name: "Retro 80s Disco Birthday",
    category: "Birthday",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #00b0ff 0%, #aa00ff 100%)",
      accentColor: "#00e5ff",
      emoji: "🪩",
      host: "Hosted by Marcus & Friends",
      venue: "Rollerland Lounge",
      description: "A throwback 80s roller disco party with synth-pop hits, arcade games, and vintage cocktails.",
      imageUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#0D041E",
      textColor: "#E1F5FE",
      titleSize: 48,
      fontWeight: "800",
      fontFamily: "Poppins",
      buttonColor: "#00e5ff",
      buttonRadius: 16,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-birthday-5",
    name: "Tropical Poolside Birthday",
    category: "Birthday",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #e0f7fa 0%, #80deea 100%)",
      accentColor: "#00acc1",
      emoji: "🍹",
      host: "Hosted by Chloe",
      venue: "Azure Palms Resort Pool",
      description: "Beat the heat with cabana lounge chairs, tropical smoothies, pool floaties, and BBQ.",
      imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#F0FAFC",
      textColor: "#00363A",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Montserrat",
      buttonColor: "#00acc1",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-birthday-6",
    name: "Wild Safari Kids Birthday",
    category: "Birthday",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #fff3e0 0%, #ffe0b2 100%)",
      accentColor: "#fb8c00",
      emoji: "🦒",
      host: "Hosted by The Johnson Family",
      venue: "Jungle Adventure Park",
      description: "Join us for a roar-some 4th birthday with face painting, pet zoo, and jungle cake!",
      imageUrl: "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#FFFDF7",
      textColor: "#3E1E00",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Inter",
      buttonColor: "#fb8c00",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-birthday-7",
    name: "Cosmic Galaxy Birthday Bash",
    category: "Birthday",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #1a237e 0%, #311b92 100%)",
      accentColor: "#7c4dff",
      emoji: "🚀",
      host: "Hosted by Lucas",
      venue: "Stargazer Planetarium",
      description: "Explore the cosmos with laser star shows, galaxy cupcakes, and space trivia.",
      imageUrl: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#0D1137",
      textColor: "#EDE7F6",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Outfit",
      buttonColor: "#7c4dff",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-birthday-8",
    name: "Speakeasy Cocktail Birthday",
    category: "Birthday",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #263238 0%, #102027 100%)",
      accentColor: "#ffb74d",
      emoji: "🥃",
      host: "Hosted by Brandon",
      venue: "The Velvet Cellar Lounge",
      description: "Step through the hidden doorway for craft cocktails, jazz piano, and a Prohibition-era celebration.",
      imageUrl: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#141C20",
      textColor: "#FFF3E0",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Lora",
      buttonColor: "#ffb74d",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-birthday-9",
    name: "Superhero Training Academy",
    category: "Birthday",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #b71c1c 0%, #0d47a1 100%)",
      accentColor: "#ffeb3b",
      emoji: "🦸‍♂️",
      host: "Hosted by The Hero Squad",
      venue: "Hero Action Zone",
      description: "Put on your favorite superhero cape for an obstacle course training, superhero cake, and prizes!",
      imageUrl: "https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#160505",
      textColor: "#FFFDE7",
      titleSize: 46,
      fontWeight: "800",
      fontFamily: "Montserrat",
      buttonColor: "#ffeb3b",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-birthday-10",
    name: "Enchanted Fairytale Garden",
    category: "Birthday",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #f3e5f5 0%, #e1bee7 100%)",
      accentColor: "#8e24aa",
      emoji: "🦄",
      host: "Hosted by Ella's Parents",
      venue: "Mystic Garden Pavilion",
      description: "Fairy wings, magic wand craft tables, tea parties, and whimsical fairytale stories.",
      imageUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#FAF5FC",
      textColor: "#2D003B",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Playfair Display",
      buttonColor: "#8e24aa",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },

  // ==================== COMMUNITY (10) ====================
  {
    id: "tpl-community-1",
    name: "Neighborhood Summer BBQ",
    category: "Community",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #fff3e0 0%, #ffe0b2 100%)",
      accentColor: "#e65100",
      emoji: "🍔",
      host: "Hosted by Oakwood HOA",
      venue: "Oakwood Park Meadows",
      description: "Bring your favorite side dish! We'll provide grilled burgers, cold drinks, lawn games, and live music.",
      imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#FFFBF5",
      textColor: "#3A1400",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Inter",
      buttonColor: "#e65100",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-community-2",
    name: "Community Farmers Market Day",
    category: "Community",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #f1f8e9 0%, #c8e6c9 100%)",
      accentColor: "#33691e",
      emoji: "🍎",
      host: "Hosted by Town Green Alliance",
      venue: "Town Center Plaza",
      description: "Support local farmers and makers! Fresh organic vegetables, baked bread, artisanal honey, and live acoustic music.",
      imageUrl: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#F7FAF5",
      textColor: "#13290B",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Lora",
      buttonColor: "#33691e",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-community-3",
    name: "Annual Block Party Celebration",
    category: "Community",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #e3f2fd 0%, #bbdefb 100%)",
      accentColor: "#1565c0",
      emoji: "🎈",
      host: "Hosted by Main St Neighbors",
      venue: "Main Street Pedestrian Zone",
      description: "Bouncy castles for kids, food trucks, street chalk competition, and open mic performances.",
      imageUrl: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#F4F9FD",
      textColor: "#062247",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Montserrat",
      buttonColor: "#1565c0",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-community-4",
    name: "Green Earth Beach Cleanup",
    category: "Community",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #e0f2f1 0%, #b2dfdb 100%)",
      accentColor: "#00695c",
      emoji: "🌊",
      host: "Hosted by Ocean Action Club",
      venue: "Sunset Cove Beach",
      description: "Join fellow environmental enthusiasts for a morning beach cleanup. Cleanup gloves and refreshments provided!",
      imageUrl: "https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#F2FAF9",
      textColor: "#002B26",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Inter",
      buttonColor: "#00695c",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-community-5",
    name: "Local Art & Craft Fair",
    category: "Community",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #f3e5f5 0%, #d1c4e9 100%)",
      accentColor: "#6a1b9a",
      emoji: "🎨",
      host: "Hosted by Civic Arts Guild",
      venue: "Community Arts Center",
      description: "Discover handmade pottery, original paintings, handmade jewelry, and local woodwork from talented artists.",
      imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#FAF5FC",
      textColor: "#250538",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Outfit",
      buttonColor: "#6a1b9a",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-community-6",
    name: "Cultural Heritage Festival",
    category: "Community",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #fff8e1 0%, #ffe082 100%)",
      accentColor: "#f57f17",
      emoji: "🌏",
      host: "Hosted by Cultural Diversity Council",
      venue: "Unity Heritage Park",
      description: "Experience vibrant international dance performances, traditional folk music, global food stalls, and workshops.",
      imageUrl: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#FFFDF5",
      textColor: "#3D1E00",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Playfair Display",
      buttonColor: "#f57f17",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },

  {
    id: "tpl-community-8",
    name: "Open Air Cinema Under Stars",
    category: "Community",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #1a237e 0%, #121858 100%)",
      accentColor: "#ffca28",
      emoji: "🎬",
      host: "Hosted by Parks & Rec",
      venue: "Central Park Amphitheater",
      description: "Pack lawn blankets and folding chairs for a family-friendly film screening under the stars. Free popcorn!",
      imageUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#0C1038",
      textColor: "#FFFDE7",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Poppins",
      buttonColor: "#ffca28",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-community-9",
    name: "Community Garden Harvest Festival",
    category: "Community",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #e8f5e9 0%, #c8e6c9 100%)",
      accentColor: "#2e7d32",
      emoji: "🌻",
      host: "Hosted by Green Thumb Society",
      venue: "Green Thumb Gardens",
      description: "Celebrate the autumn harvest with fresh cider, pumpkin painting, seed sharing workshops, and garden tours.",
      imageUrl: "https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#F4FAF4",
      textColor: "#0B260C",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Lora",
      buttonColor: "#2e7d32",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-community-10",
    name: "Holiday Toy & Food Drive",
    category: "Community",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #ffebee 0%, #e8f5e9 100%)",
      accentColor: "#b71c1c",
      emoji: "🎁",
      host: "Hosted by Community Care Network",
      venue: "Civic Community Hall",
      description: "Help us collect unwrapped toys and non-perishable food items for local families in need this holiday season.",
      imageUrl: "https://images.unsplash.com/photo-1512909006721-3d6018887383?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#FAF5F5",
      textColor: "#2E0505",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Merriweather",
      buttonColor: "#b71c1c",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },

  // ==================== NETWORKING (10) ====================
  {
    id: "tpl-networking-1",
    name: "Founders & Coffee Morning",
    category: "Networking",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #efebe9 0%, #d7ccc8 100%)",
      accentColor: "#5d4037",
      emoji: "☕",
      host: "Hosted by Founder Collective",
      venue: "Roastery Social Loft",
      description: "An informal morning coffee social for startup founders, tech builders, and early-stage investors.",
      imageUrl: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#FAF8F7",
      textColor: "#2A1C18",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Inter",
      buttonColor: "#5d4037",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-networking-2",
    name: "Women in Tech Leaders Summit",
    category: "Networking",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #f3e5f5 0%, #e1bee7 100%)",
      accentColor: "#8e24aa",
      emoji: "👩‍💻",
      host: "Hosted by WomenTech Global",
      venue: "Horizon Tower Auditorium",
      description: "Empowering keynote talks, mentorship speed-matching, and evening networking drinks with top female tech executives.",
      imageUrl: "https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#FAF5FC",
      textColor: "#2D003B",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Montserrat",
      buttonColor: "#8e24aa",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-networking-3",
    name: "Creative Directors Roundtable",
    category: "Networking",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #212121 0%, #424242 100%)",
      accentColor: "#ff6d00",
      emoji: "✒️",
      host: "Hosted by Design District Guild",
      venue: "Modernist Studio 4",
      description: "An evening for art directors, UX leads, and brand strategists to discuss emerging creative trends.",
      imageUrl: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#161616",
      textColor: "#FAFAFA",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Outfit",
      buttonColor: "#ff6d00",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-networking-4",
    name: "Biotech & Healthcare Mixer",
    category: "Networking",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #e0f2f1 0%, #80cbc4 100%)",
      accentColor: "#00796b",
      emoji: "🧬",
      host: "Hosted by BioHealth Alliance",
      venue: "Innovation Campus Hall",
      description: "Connecting medical researchers, pharma pioneers, and healthcare investors for prospective collaborations.",
      imageUrl: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#F2FAF9",
      textColor: "#00332D",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Inter",
      buttonColor: "#00796b",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-networking-5",
    name: "Real Estate Investor Night",
    category: "Networking",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #1a237e 0%, #283593 100%)",
      accentColor: "#c0ca33",
      emoji: "🏢",
      host: "Hosted by Metro Realty Club",
      venue: "Metropolitan Sky Lounge",
      description: "Network with commercial brokers, residential developers, private lenders, and REIT fund managers.",
      imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#0D113C",
      textColor: "#F9FBE7",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Montserrat",
      buttonColor: "#c0ca33",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-networking-6",
    name: "Startup Speed Networking",
    category: "Networking",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #e8f5e9 0%, #a5d6a7 100%)",
      accentColor: "#1b5e20",
      emoji: "⚡",
      host: "Hosted by Venture Launchpad",
      venue: "Venture Hub Co-working",
      description: "Structured 5-minute speed networking rounds designed to connect technical developers with business strategists.",
      imageUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#F4FAF5",
      textColor: "#0A240C",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Inter",
      buttonColor: "#1b5e20",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-networking-7",
    name: "Global Professionals Evening",
    category: "Networking",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #311b92 0%, #4527a0 100%)",
      accentColor: "#ffd54f",
      emoji: "🌐",
      host: "Hosted by Expat Business Club",
      venue: "Skyline Regency Bar",
      description: "Join international expats, diplomats, and global business executives for an evening of networking and wine.",
      imageUrl: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#130A3A",
      textColor: "#FFFDE7",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Playfair Display",
      buttonColor: "#ffd54f",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-networking-8",
    name: "Young Professionals Social Mixer",
    category: "Networking",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #ffe0b2 0%, #ffcc80 100%)",
      accentColor: "#e65100",
      emoji: "🍻",
      host: "Hosted by Metro YP Network",
      venue: "Urban Taphouse & Grill",
      description: "Relaxed happy hour networking for ambition-driven early-career professionals across all corporate sectors.",
      imageUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#FFFBF5",
      textColor: "#3A1400",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Poppins",
      buttonColor: "#e65100",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-networking-9",
    name: "Alumni Industry Network Night",
    category: "Networking",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #880e4f 0%, #ad1457 100%)",
      accentColor: "#ff80ab",
      emoji: "🎓",
      host: "Hosted by University Alumni Board",
      venue: "The University Club",
      description: "Re-engage with university alumni across technology, finance, medicine, law, and arts industries.",
      imageUrl: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#240415",
      textColor: "#FCE4EC",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Lora",
      buttonColor: "#ff80ab",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-networking-10",
    name: "Digital Nomads & Remote Tech Social",
    category: "Networking",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #e0f7fa 0%, #b2ebf2 100%)",
      accentColor: "#0097a7",
      emoji: "🌴",
      host: "Hosted by Nomad Co-op",
      venue: "Coastal Sunset Bar",
      description: "Sunset drinks and casual networking for remote developers, freelancers, agency owners, and digital nomads.",
      imageUrl: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#F0FAFC",
      textColor: "#003C43",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Outfit",
      buttonColor: "#0097a7",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },

  // ==================== PRIVATE DINNER (10) ====================
  {
    id: "tpl-privatedinner-1",
    name: "Chef's Wine & Tasting Dinner",
    category: "Private Dinner",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #4a0072 0%, #2a003d 100%)",
      accentColor: "#e040fb",
      emoji: "🍷",
      host: "Hosted by Chef Jean-Luc",
      venue: "La Maison Gourmet",
      description: "Indulge in a 7-course seasonal tasting menu expertly paired with rare vintage French wines.",
      imageUrl: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#160022",
      textColor: "#FAFAFA",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Playfair Display",
      buttonColor: "#e040fb",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-privatedinner-2",
    name: "Candlelit Garden Supper",
    category: "Private Dinner",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #33691e 0%, #1b5e20 100%)",
      accentColor: "#aed581",
      emoji: "🕯️",
      host: "Hosted by Amara & Friends",
      venue: "The Secret Courtyard",
      description: "Warm candlelit tables under olive trees, serving wood-fired artisanal cuisine and organic wines.",
      imageUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#0D1F08",
      textColor: "#F1F8E9",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Lora",
      buttonColor: "#aed581",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-privatedinner-3",
    name: "Penthouse Sky Dining",
    category: "Private Dinner",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #1c3144 0%, #0f172a 100%)",
      accentColor: "#ffb74d",
      emoji: "🌃",
      host: "Hosted by Executive Club",
      venue: "Penthouse 88 Lounge",
      description: "Panoramics skyline views accompanied by caviar service, wagyu beef, and craft mixology.",
      imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#0B1220",
      textColor: "#FFF3E0",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Cinzel",
      buttonColor: "#ffb74d",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-privatedinner-4",
    name: "Tuscan Feast Under The Stars",
    category: "Private Dinner",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #d84315 0%, #bf360c 100%)",
      accentColor: "#ffab91",
      emoji: "🍝",
      host: "Hosted by The Rossi Family",
      venue: "Vineyard Villa Terrace",
      description: "Handmade pasta, wood-roasted meats, freshly baked focaccia, and Chianti wine flow freely.",
      imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#2B0B03",
      textColor: "#FBE9E7",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Merriweather",
      buttonColor: "#ffab91",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-privatedinner-5",
    name: "Omakase Culinary Experience",
    category: "Private Dinner",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #212121 0%, #000000 100%)",
      accentColor: "#e53935",
      emoji: "🍣",
      host: "Hosted by Chef Master Kenji",
      venue: "Zen Sushi Atelier",
      description: "An exclusive 12-seat counter omakase experience featuring pristine seasonal seafood flown directly from Tokyo.",
      imageUrl: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#121212",
      textColor: "#FFEBEE",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Inter",
      buttonColor: "#e53935",
      buttonRadius: 6,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-privatedinner-6",
    name: "Speakeasy Secret Supper Club",
    category: "Private Dinner",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #3e2723 0%, #1b0000 100%)",
      accentColor: "#d7ccc8",
      emoji: "🔑",
      host: "Hosted by Culinary Society",
      venue: "Room 1920 Secret Parlor",
      description: "Secret location disclosed 24 hours prior. Multi-course experimental dining with live jazz quartet.",
      imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#160C0A",
      textColor: "#EFEBE9",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Playfair Display",
      buttonColor: "#d7ccc8",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-privatedinner-7",
    name: "Farm-to-Table Sunset Dinner",
    category: "Private Dinner",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #f57f17 0%, #e65100 100%)",
      accentColor: "#ffe082",
      emoji: "🌾",
      host: "Hosted by Green Acre Farms",
      venue: "Organic Orchards Meadow",
      description: "Dine right alongside the harvest fields. Heirloom vegetables, pastured meats, and natural wines.",
      imageUrl: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#2B1602",
      textColor: "#FFFDE7",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Lora",
      buttonColor: "#ffe082",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-privatedinner-8",
    name: "Seafood & Champagne Soirée",
    category: "Private Dinner",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #00838f 0%, #004d40 100%)",
      accentColor: "#80deea",
      emoji: "🥂",
      host: "Hosted by The Coastal Guild",
      venue: "Oceanfront Glass Villa",
      description: "Freshly shucked oysters, grilled lobster tails, and endless pours of vintage Brut champagne.",
      imageUrl: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#031B1E",
      textColor: "#E0F7FA",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Montserrat",
      buttonColor: "#80deea",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },

  {
    id: "tpl-privatedinner-10",
    name: "Holiday Warmth Feast",
    category: "Private Dinner",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #b71c1c 0%, #1b5e20 100%)",
      accentColor: "#ffd700",
      emoji: "🕯️",
      host: "Hosted by The Sterling Family",
      venue: "Manor House Grand Dining Room",
      description: "Roast turkey, mulled wine, crackling fireplace, and warm holiday toasts among close friends.",
      imageUrl: "https://images.unsplash.com/photo-1543589077-47d81606c1bf?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#1C0404",
      textColor: "#FFFDE7",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Merriweather",
      buttonColor: "#ffd700",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },

  // ==================== FUNDRAISER (10) ====================
  {
    id: "tpl-fundraiser-1",
    name: "Hope & Healing Charity Gala",
    category: "Fundraiser",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #004d40 0%, #00251a 100%)",
      accentColor: "#ffd54f",
      emoji: "✨",
      host: "Hosted by Hope Foundation",
      venue: "Grand Marquis Ballroom",
      description: "An elegant gala evening featuring live auctions, keynotes from medical pioneers, and black-tie dinner.",
      imageUrl: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#021A15",
      textColor: "#FFFDE7",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Playfair Display",
      buttonColor: "#ffd54f",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-fundraiser-2",
    name: "Save The Oceans Ocean Gala",
    category: "Fundraiser",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #01579b 0%, #002f6c 100%)",
      accentColor: "#4fc3f7",
      emoji: "🐋",
      host: "Hosted by Blue Ocean Initiative",
      venue: "Maritime Museum Pavilion",
      description: "Help raise funds for coral reef restoration and marine wildlife protection. Silent auction & dinner.",
      imageUrl: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#021A30",
      textColor: "#E0F7FA",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Montserrat",
      buttonColor: "#4fc3f7",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-fundraiser-3",
    name: "Wildlife Conservation Benefit",
    category: "Fundraiser",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #33691e 0%, #1b5e20 100%)",
      accentColor: "#ffb74d",
      emoji: "🐅",
      host: "Hosted by World Wildlife Alliance",
      venue: "Natural History Pavilion",
      description: "Raising funds for anti-poaching teams and endangered species habitat conservation.",
      imageUrl: "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#0A1F08",
      textColor: "#FFF3E0",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Lora",
      buttonColor: "#ffb74d",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-fundraiser-4",
    name: "Children's Health Gala Night",
    category: "Fundraiser",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #880e4f 0%, #4a0072 100%)",
      accentColor: "#ff4081",
      emoji: "❤️",
      host: "Hosted by St. Jude Auxiliary",
      venue: "St. Jude Convention Center",
      description: "100% of ticket sales go directly toward pediatric cancer research and patient care.",
      imageUrl: "https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#1F0314",
      textColor: "#FCE4EC",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Outfit",
      buttonColor: "#ff4081",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-fundraiser-5",
    name: "Clean Water Initiative Gala",
    category: "Fundraiser",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #00838f 0%, #004d40 100%)",
      accentColor: "#80deea",
      emoji: "💧",
      host: "Hosted by Pure Water Fund",
      venue: "Aquatic Palace Hall",
      description: "An inspiring evening dedicated to building clean water wells in drought-affected rural villages.",
      imageUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#031C1F",
      textColor: "#E0F7FA",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Inter",
      buttonColor: "#80deea",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-fundraiser-6",
    name: "Arts & Culture Foundation Ball",
    category: "Fundraiser",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #311b92 0%, #1a237e 100%)",
      accentColor: "#ffd700",
      emoji: "🎻",
      host: "Hosted by Civic Arts Endowment",
      venue: "Symphony Hall Rotunda",
      description: "Live orchestral performances, ballet showcases, and silent art auction in support of youth art programs.",
      imageUrl: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#0F0933",
      textColor: "#FFFDE7",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Playfair Display",
      buttonColor: "#ffd700",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-fundraiser-7",
    name: "Scholarship Fund Golf Classic",
    category: "Fundraiser",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #2e7d32 0%, #1b5e20 100%)",
      accentColor: "#ffeb3b",
      emoji: "⛳",
      host: "Hosted by Higher Ed Foundation",
      venue: "Greenbrier Country Club",
      description: "18-hole scramble tournament, lunch buffet, award ceremony, and silent auction raising college scholarships.",
      imageUrl: "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#0B260D",
      textColor: "#FFFDE7",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Inter",
      buttonColor: "#ffeb3b",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-fundraiser-8",
    name: "Empower Women Leadership Gala",
    category: "Fundraiser",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #c2185b 0%, #880e4f 100%)",
      accentColor: "#f8bbd0",
      emoji: "👑",
      host: "Hosted by Empower Her Global",
      venue: "Metropolitan Convention Center",
      description: "Keynotes from prominent female founders, micro-loan grant presentations, and networking dinner.",
      imageUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#290413",
      textColor: "#FCE4EC",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Montserrat",
      buttonColor: "#f8bbd0",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-fundraiser-9",
    name: "Disaster Relief Benefit Concert",
    category: "Fundraiser",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #b71c1c 0%, #7f0000 100%)",
      accentColor: "#ff8a80",
      emoji: "🎸",
      host: "Hosted by Global Red Cross",
      venue: "Civic Arena Amphitheater",
      description: "Star-studded benefit concert bringing immediate food, shelter, and medical relief to disaster zones.",
      imageUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#260404",
      textColor: "#FFEBEE",
      titleSize: 48,
      fontWeight: "800",
      fontFamily: "Outfit",
      buttonColor: "#ff8a80",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-fundraiser-10",
    name: "Tech For Good Foundation Dinner",
    category: "Fundraiser",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #0288d1 0%, #01579b 100%)",
      accentColor: "#b3e5fc",
      emoji: "💻",
      host: "Hosted by Tech Cares Alliance",
      venue: "Innovation Pavilion",
      description: "Tech industry leaders gather to raise $5M for AI-driven logistics solving urban food waste.",
      imageUrl: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#021E36",
      textColor: "#E1F5FE",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Inter",
      buttonColor: "#b3e5fc",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },

  // ==================== GRADUATION (10) ====================
  {
    id: "tpl-graduation-1",
    name: "Doctorate & PhD Commencement Gala",
    category: "Graduation",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #4a148c 0%, #1a237e 100%)",
      accentColor: "#ffd700",
      emoji: "🎓",
      host: "Hosted by Office of the Dean",
      venue: "Grand Alumni Hall",
      description: "An elegant evening celebrating years of doctoral research, dissertation defense, and academic achievement.",
      imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#120524",
      textColor: "#FFFDE7",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Playfair Display",
      buttonColor: "#ffd700",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-graduation-2",
    name: "High School Senior Farewell Party",
    category: "Graduation",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #ff6f00 0%, #e65100 100%)",
      accentColor: "#ffe082",
      emoji: "🎉",
      host: "Hosted by Senior Class Committee",
      venue: "Sunset Beach Pavilion",
      description: "DJ dance floor, memory slideshow wall, food trucks, and cap tossing celebration as high school ends!",
      imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#2B0D00",
      textColor: "#FFFDE7",
      titleSize: 48,
      fontWeight: "800",
      fontFamily: "Outfit",
      buttonColor: "#ffe082",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-graduation-3",
    name: "Medical School White Coat Banquet",
    category: "Graduation",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #0277bd 0%, #01579b 100%)",
      accentColor: "#81d4fa",
      emoji: "🩺",
      host: "Hosted by School of Medicine",
      venue: "University Health Science Hall",
      description: "Celebrating the oath of medicine, white coat presentation, and new residency matching achievements.",
      imageUrl: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#021D2E",
      textColor: "#E0F7FA",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Montserrat",
      buttonColor: "#81d4fa",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-graduation-4",
    name: "Law School Juris Doctor Gala",
    category: "Graduation",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #3e2723 0%, #1b0000 100%)",
      accentColor: "#d7ccc8",
      emoji: "⚖️",
      host: "Hosted by School of Law Alumni",
      venue: "Justice Hall Grand Room",
      description: "An esteemed dinner honoring our Juris Doctor graduates as they prepare to take the bar examination.",
      imageUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#170D0B",
      textColor: "#EFEBE9",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Cinzel",
      buttonColor: "#d7ccc8",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-graduation-5",
    name: "Engineering & STEM Grad Party",
    category: "Graduation",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #00838f 0%, #004d40 100%)",
      accentColor: "#00e5ff",
      emoji: "⚙️",
      host: "Hosted by College of Engineering",
      venue: "Robotics Tech Loft",
      description: "Showcasing capstone engineering projects, AI prototypes, and celebrating computer science degrees.",
      imageUrl: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#031C1E",
      textColor: "#E0F7FA",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Inter",
      buttonColor: "#00e5ff",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-graduation-6",
    name: "Arts & Design Graduate Showcase",
    category: "Graduation",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #37474f 0%, #212121 100%)",
      accentColor: "#ff4081",
      emoji: "🎨",
      host: "Hosted by Academy of Fine Arts",
      venue: "Design Academy Loft Gallery",
      description: "Exhibition of senior thesis artwork, fashion design runway, film screening, and cocktail reception.",
      imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#161B1E",
      textColor: "#FAFAFA",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Outfit",
      buttonColor: "#ff4081",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-graduation-7",
    name: "Business School MBA Celebration",
    category: "Graduation",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #1a237e 0%, #0d47a1 100%)",
      accentColor: "#c0ca33",
      emoji: "💼",
      host: "Hosted by MBA Graduate Association",
      venue: "Executive Lounge Regency",
      description: "An evening for MBA graduates, faculty, and industry sponsors to toast to future business triumphs.",
      imageUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#0A103D",
      textColor: "#F9FBE7",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Lora",
      buttonColor: "#c0ca33",
      buttonRadius: 8,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-graduation-8",
    name: "Kindergarten Cap & Gown Party",
    category: "Graduation",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #fff8e1 0%, #ffe082 100%)",
      accentColor: "#f57c00",
      emoji: "🐥",
      host: "Hosted by Little Scholars Academy",
      venue: "Little Scholars Auditorium",
      description: "Adorable tiny cap and gown diploma presentation, juice box toasts, and cupcake celebration!",
      imageUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#FFFDF7",
      textColor: "#3A1B00",
      titleSize: 46,
      fontWeight: "700",
      fontFamily: "Poppins",
      buttonColor: "#f57c00",
      buttonRadius: 12,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-graduation-9",
    name: "Nursing Graduate Pinning Ceremony",
    category: "Graduation",
    isPremium: false,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #e0f2f1 0%, #80cbc4 100%)",
      accentColor: "#00897b",
      emoji: "🩺",
      host: "Hosted by College of Nursing",
      venue: "Mercy Auditorium",
      description: "Traditional nursing pin presentation, candle lighting ceremony, and reception for family and friends.",
      imageUrl: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#F2FAF9",
      textColor: "#003630",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Inter",
      buttonColor: "#00897b",
      buttonRadius: 10,
      textAlignment: "center"
    })
  },
  {
    id: "tpl-graduation-10",
    name: "Master's Degree Award Banquet",
    category: "Graduation",
    isPremium: true,
    content: JSON.stringify({
      gradient: "linear-gradient(135deg, #1b5e20 0%, #003300 100%)",
      accentColor: "#aed581",
      emoji: "📜",
      host: "Hosted by Graduate Student Council",
      venue: "Skyline Regency Room",
      description: "Formal dinner celebrating Master of Science and Master of Arts recipients across all departments.",
      imageUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=80",
      backgroundColor: "#0B210B",
      textColor: "#F1F8E9",
      titleSize: 48,
      fontWeight: "700",
      fontFamily: "Merriweather",
      buttonColor: "#aed581",
      buttonRadius: 10,
      textAlignment: "center"
    })
  }
];

const newTemplateStylesBackend = newTemplatesDataBackend.reduce((acc, t) => {
  const content = JSON.parse(t.content);
  acc[t.id] = {
    imageUrl: content.imageUrl,
    accentColor: content.accentColor,
    backgroundColor: content.backgroundColor,
    textColor: content.textColor,
    titleSize: content.titleSize,
    fontWeight: content.fontWeight,
    fontFamily: content.fontFamily,
    buttonColor: content.buttonColor,
    buttonRadius: content.buttonRadius,
    textAlignment: content.textAlignment
  };
  return acc;
}, {});

module.exports = {
  newTemplatesDataBackend,
  newTemplateStylesBackend
};
